AgriService/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls')),
]

service/urls.py
from django.urls import path
from . import views

app_name = 'service'

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='index'),
    path('about_us/', views.AboutUsTemplateView.as_view(), name='about_us'),
    path('contact/', views.ContactTemplateView.as_view(), name='signup'),
    path('signup/', views.signup, name='account'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('account/', views.AccountTemplateView.as_view(), name='contact'),
]

service/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=20)

service/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ValidationError
from .models import *


class SignupForm(UserCreationForm):
    name = forms.CharField(required=False, )
    email = forms.CharField(required=True)
    password1 = forms.PasswordInput()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'name']

    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError('The given email is already registered')
        return self.cleaned_data['email']

service/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm
from django.contrib.auth import login, logout, authenticate
from django.views.generic import TemplateView
from .models import *


class IndexTemplateView(TemplateView):
    template_name = 'index.html'


class AboutUsTemplateView(TemplateView):
    template_name = 'about_us.html'


class ContactTemplateView(TemplateView):
    template_name = 'contact.html'


class AccountTemplateView(TemplateView):
    template_name = 'account.html'


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('service:home')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})


class HomeView(TemplateView):
    template_name = 'home.html'


def test():
    pass

service/templates/account.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title%} Account {% endblock %}

{% block body %}
         <!--Inner Header Start-->
         <section class=" p100 inner-header">
            <div class="container">
               <h1>My Account</h1>
               <ul>
                  <li><a href="#">Home</a></li>
                  <li><a href="#"> My Account </a></li>
               </ul>
            </div>
         </section>
         <!--Inner Header End-->
         <!--Causes Start-->
         <section class="wf100 p80">
            <div class="container">
               <div class="row">
                  <div class="col-lg-8">
                     <div class="myaccount-form">
                        <h3>Register Your Account</h3>
                        <form method="post" novalidate>

                           <ul class="row">
                              <li class="col-md-6">
                                 <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Your Name" required>
                                 </div>
                              </li>
                              <li class="col-md-6">
                                 <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Contact #" required>
                                 </div>
                              </li>
                              <li class="col-md-6">
                                 <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Email Address" required>
                                 </div>
                              </li>
                              <li class="col-md-6">
                                 <div class="input-group">
                                    <input type="text" class="form-control" placeholder="User Name">
                                 </div>
                              </li>
                              <li class="col-md-6">
                                 <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Password">
                                 </div>
                              </li>
                              <li class="col-md-6">
                                 <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Re-enter Password">
                                 </div>
                              </li>
                              <li class="col-md-12">
                                 <div class="input-group form-check">
                                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                    <label class="form-check-label" for="exampleCheck1">I agree to the Terms of <a href="#">Services & Privacy Plicy</a></label>
                                 </div>
                              </li>
                              <li class="col-md-12">
                                 <button class="register">Register Your Account</button>
                              </li>
                           </ul>
                        </form>
                     </div>
                  </div>
                  <div class="col-lg-4">
                     <div class="login-box">
                        <h3>Login Account</h3>
                        <form>
                           <div class="input-group">
                              <input type="text" class="form-control" placeholder="Username/Email" required>
                           </div>
                           <div class="input-group">
                              <input type="password" class="form-control" placeholder="Password" required>
                           </div>
                           <div class="input-group form-check">
                              <input type="checkbox" class="form-check-input" id="exampleCheck2">
                              <label class="form-check-label" for="exampleCheck2">Remember Me</label>
                              <a href="#" class="fp">Forgot Password</a>
                           </div>
                           <div class="input-group">
                              <button class="login-btn">Login Account</button>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </section>
         <!--Causes End-->
{% endblock %}

service/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Contact {% endblock %}
{% block body %}
         <!--Inner Header Start-->
         <section class="wf100 p100 inner-header">
            <div class="container">
               <h1>Contact Us</h1>
               <ul>
                  <li><a href="{% url 'service:index' %}">Home</a></li>
                  <li><a href="#"> Contact </a></li>
               </ul>
            </div>
         </section>
         <!--Inner Header End-->
         <!--Contact Start-->
         <section class="contact-page wf100 p80">
            <div class="container">
               <div class="row">
                  <div class="col-md-6">
                     <div class="contact-form">
                        <h3>Feel Free to Contact us</h3>
                        <ul class="cform">
                           <li class="half pr-15">
                              <input type="text" class="form-control" placeholder="Full Name">
                           </li>
                           <li class="half pl-15">
                              <input type="text" class="form-control" placeholder="Email">
                           </li>
                           <li class="half pr-15">
                              <input type="text" class="form-control" placeholder="Contact">
                           </li>
                           <li class="half pl-15">
                              <input type="text" class="form-control" placeholder="Subject">
                           </li>
                           <li class="full">
                              <textarea class="textarea-control" placeholder="Message"></textarea>
                           </li>
                           <li class="full">
                              <input type="submit" value="Contact us" class="fsubmit">
                           </li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="google-map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11418.310112375979!2d-74.00986187433132!3d40.710981182716246!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew+York%2C+NY!5e0!3m2!1sen!2s!4v1540972202179"></iframe>
                     </div>
                  </div>
               </div>
            </div>
            <div class="container contact-info">
               <div class="row">
                  <div class="col-md-12">
                     <h3>Contact Information</h3>
                  </div>
                  <!--Contact Info Start-->
                  <div class="col-md-4">
                     <div class="c-info">
                        <h6>Address:</h6>
                        <p> 4700 Millenia Blvd # 175, NRB, FL 32839, kENYA </p>
                     </div>
                  </div>
                  <!--Contact Info End-->
                  <!--Contact Info Start-->
                  <div class="col-md-4">
                     <div class="c-info">
                        <h6>Contact:</h6>
                        <p><strong>Phone:</strong> +1 321 2345 678-9</p>
                        <p><strong>Fax:</strong> +1 321 2345 876-7</p>
                     </div>
                  </div>
                  <!--Contact Info End-->
                  <!--Contact Info Start-->
                  <div class="col-md-4">
                     <div class="c-info">
                        <h6>For More Information:</h6>
                        <p><strong>Email:</strong> info@turimi.com</p>
                        <p>contact@turimi.com</p>
                     </div>
                  </div>
                  <!--Contact Info End-->
               </div>
            </div>
         </section>
         <!--Contact End-->
{% endblock %}

service/templates/home.html
{% extends 'base_app.html' %}
{% block title %} home {% endblock %}
{% block body %}
    <div class="">
        <h3>Welcome <strong>{{ user.username }}</strong></h3>
    </div>
{% endblock %}

service/templates/index.html
{% extends 'base.html' %}
{% load static%}
{% block title %}Turi Mei{% endblock %}
{% block body %}

            <!--Slider Start-->
        <section id="home-slider" class="owl-carousel owl-theme wf100">
        <div class="item" style="overflow: unset">
        <div class="slider-caption h2slider">
          <div class="container">
             <strong>Turi Mei<span> is the Best</span></strong>
             <h1>farmer's point</h1>
             <p>Connecting agricultural services</p>
             <a href="#" class="active">Find Out More</a> <a href="#">Join us Now</a>
          </div>
        </div>
        <img src="{% static 'images/my_images/hslide1.jpg' %}" alt="">
        </div>
        <div class="item">
        <div class="slider-caption h2slider">
          <div class="container">
             <strong><span>Engage</span> with our </strong>
             <h1>Partners</h1>
             <p>to <strong>access unexplored</strong> markets</p>
             <a href="#" class="active">Find Out More</a> <a href="#">Join us Now</a>
          </div>
        </div>
        <img src="{% static 'images/my_images/hslide2.jpg' %}" alt="">
        </div>
        <div class="item">
        <div class="slider-caption h2slider">
          <div class="container">
             <strong>Save <span> on farming expenses</span></strong>
             <h1>Access resources </h1>
             <p>At <strong>your own convenience through </strong> our partners...</p>
             <a href="#" class="active">Find Out More</a> <a href="#">Join us Now</a>
          </div>
        </div>
        <img src="{% static 'images/my_images/hslide3.jpg' %}" alt="">
        </div>
        </section>
        <!--Slider End-->
        <!--Service Area Start-->
         <!--Service Area Start-->
         <section class="services-area wf100">
            <div class="container">
               <ul>
                  <!--box  start-->
                  <li>
                     <div class="sinfo">
                        <img src="{% static 'images/my_images/sericon_pigs.png' %}" alt="">
                        <h6>Agrovet</h6>
                        <p> Farmer's Supply Store</p>
                     </div>
                  </li>
                  <!--box  end-->
                  <!--box  start-->
                  <li>
                     <div class="sinfo">
                        <img src="{% static 'images/my_images/sericon_team.png' %}" alt="">
                        <h6>Consultancy</h6>
                        <p>Resources & Financial Advice</p>
                     </div>
                  </li>
                  <!--box  end-->
                  <!--box  start-->
                  <li>
                     <div class="sinfo">
                        <img src="{% static 'images/my_images/sericon_market.png' %}" alt="">
                        <h6>Product Marketing</h6>
                        <p> Reach Consumers Faster</p>
                     </div>
                  </li>
                  <!--box  end-->
                  <!--box  start-->
                  <li class="active">
                     <div class="sinfo">
                        <img src="{% static 'images/my_images/sericon_rake.png' %}" alt="">
                        <h6> Tools Supply</h6>
                        <p>Farming Product and Equipment</p>
                     </div>
                  </li>
                  <!--box  end-->
                  <!--box  start-->
                  <li>
                     <div class="sinfo">
                        <img src="{% static 'images/my_images/sericon_loan.png' %}" alt="">
                        <h6>MoA Subsidy</h6>
                        <p>Stimulus Package for Farming</p>
                     </div>
                  </li>
                  <!--box  end-->
               </ul>
            </div>
         </section>
         <!--Service Area End-->
         <!--About Section Start-->
         <section class="home2-about wf100 p100 gallery">
            <div class="container">
               <div class="row">
                  <div class="col-md-5">
                     <div class="video-img"><img src="{% static 'images/my_images/about.jpg' %}" alt=""> </div>
                  </div>
                  <div class="col-md-7">
                     <div class="h2-about-txt">
                        <h3>About Turi Mei</h3>
                        <h2>All farming services can be integrated under one roof.</h2>
                        <p> If anything’s hot in today’s economy, it's saving money, while optimizing your profits, including a broad range of AgriServices helping farmers access critical resources. </p>
                        <a class="aboutus" href="{% url 'service:about_us' %}">More About us</a>
                     </div>
                  </div>
               </div>
            </div>

         </section>
         <!--About Section End-->
         <!--Why Ecova + Facts Start-->
         <section class="why-ecova wf100" style="background: {% static 'images/my_images/whybg.jpg' %} no-repeat">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <h1> Why Turi Mei !</h1>
                     <p>We are ambitious and and rapidly growing start up aiming to improve accessibility to farming services. Let's join
                         us to do somithing awesome for Kenya's agricultural sector
                     </p>
                     <a href="#" class="cus">Signup to Join us</a>
                  </div>
               </div>
            </div>
         </section>
         <!--Why Ecova + Facts End-->
         <!--News & Articles Start-->
         <section class="h2-news wf100 p80">
            <div class="container">
               <div class="row">
                  <div class="col-md-6">
                     <div class="section-title-2">
                        <h5>Read Our Latest</h5>
                        <h2>News & Articles</h2>
                     </div>
                  </div>
                  <div class="col-md-6"> <a href="#" class="view-more">View More News</a> </div>
               </div>
               <div class="row">
                  <div class="col-md-6">
                     <div class="blog-post-large">
                        <div class="post-thumb"> <a href="#"><i class="fas fa-link"></i></a> <img src="{% static 'images/my_images/farmer.jpg' %}" alt=""></div>
                        <div class="post-txt">
                           <ul class="post-meta">
                              <li><i class="fas fa-calendar-alt"></i> 29 January, 2022</li>
                              <li><i class="fas fa-comments"></i> 134 Comments</li>
                           </ul>
                           <h5><a href="#">Farming our lands for Better Future</a></h5>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <!--Blog Small Post Start-->
                     <div class="blog-small-post">
                        <div class="post-thumb"> <a href="#"><i class="fas fa-link"></i></a> <img src="{% static 'images/my_images/news_chicken.jpg' %}" alt=""> </div>
                        <div class="post-txt">
                           <span class="pdate"> <i class="fas fa-calendar-alt"></i> 29 January, 2022</span>
                           <h5><a href="#">How you can market poultry.</a></h5>
                           <p>According to a survey the perceived higher cost of poultry.</p>
                           <a href="#" class="rm">Read More</a>
                        </div>
                     </div>
                     <!--Blog Small Post End-->
                     <!--Blog Small Post Start-->
                     <div class="blog-small-post">
                        <div class="post-thumb"> <a href="#"><i class="fas fa-link"></i></a> <img src="{% static 'images/my_images/news_greenhouse.jpg' %}" alt=""> </div>
                        <div class="post-txt">
                           <span class="pdate"> <i class="fas fa-calendar-alt"></i> 29 January, 2022</span>
                           <h5><a href="#">The effort to invest in greenhouse is increasing.</a></h5>
                           <p>Majority have increased interest in green house farming following.</p>
                           <a href="#" class="rm">Read More</a>
                        </div>
                     </div>
                     <!--Blog Small Post End-->
                  </div>
               </div>
            </div>
         </section>
         <!--News & Articles End-->
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/my_images/favicon4.png' %}">
    <title>{% block title %}{% endblock %}</title>
      <!-- CSS FILES START -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/color.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome-new/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'css/slick.css' %}" rel="stylesheet">
    <link href="{% static 'css/my_css.css' %}" rel="stylesheet" type="text/css" media="all">
    <link href="{% static 'css/test.css' %}" rel="stylesheet">

      <!-- CSS FILES End -->
    {% block head %}
    {% endblock %}
   </head>
   <body>
       <!-- test -->
       <!-- test--2-->
        <!-- top nav -->
        <div class="container-fluid top-nav-container p-sm-2">
            <div class="row">
                <div class="top-nav-left mb-2">
                    <a href="" class="mr-3"> <i class="fas fa-phone"></i> +254 7123456789</a>
                    <a href=""><i class="fas fa-envelope"></i> contact@tuitmei.com</a>
                </div>
                <div class="offset-lg-6 offset-2">
                    <div class="top-nav-right ">
                   <a href="" ><i class="fa fa-facebook" ></i></a>
                </div>
                <div class="top-nav-right">
                   <a href="" ><i class="fa fa-pinterest" ></i></a>
                </div>
                <div class="top-nav-right">
                   <a href="" ><i class="fa fa-twitter" ></i></a>
                </div>
                <div class="top-nav-right">
                   <a href="" ><i class="fa fa-reddit" ></i></a>
                </div>
                <div class="top-nav-right">
                   <a href="" ><i class="fa fa-linkedin" ></i></a>
                </div>
                </div>
            </div>
        </div>

        </div>

       <div class="wrapper home2">
     <!-- Top Navigation -->
{##}
{#        <ul class="nav" style="background: #1b1e21">#}
{#           <div class="container-fluid">#}
{#               <div class="row">#}
{#                    <li class="nav-item ml-lg-3">#}
{#                        <a href="#" class="nav-link" style="color: whitesmoke; font-size: 18px" ><i class="fas fa-phone"></i> +254 700-222-3333    <i class="fas fa-envelope"></i> email@turimei.com</a>#}
{#                    </li>#}
{#                   <li class="nav-item mr-auto offset-lg-7">#}
{#                        <a href="#" class="mr-3 ml-3" style="color: whitesmoke; font-size: 20px" ><i class="fab fa-facebook"></i></a>#}
{#                       <a href="#" class="mr-3" style="color: whitesmoke; font-size: 20px" ><i class="fab fa-twitter"></i></a>#}
{#                       <a href="#" class="mr-3" style="color: whitesmoke; font-size: 20px" ><i class="fab fa-whatsapp"></i></a>#}
{#                       <a href="#" class="mr-3" style="color: whitesmoke; font-size: 20px" ><i class="fab fa-instagram"></i></a>#}
{#                       <a href="#" class="mr-3" style="color: whitesmoke; font-size: 20px" ><i class="fab fa-youtube"></i></a>#}
{#                    </li>#}
{##}
{#               </div>#}
{#           </div>#}
{##}
{#        </ul>#}

        <!--Header Start-->
        <header class="header-style-2">
        <nav class="navbar navbar-expand-lg sticky-top">
        <a class="navbar-brand"  href="{% url 'service:index' %}"><img src="{% static 'images/my_images/logoo.png' %}" alt="" style="width: 210px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <i class="fas fa-bars"></i> </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"> <a class="nav-link" href="{% url 'service:index' %}">Home</a> </li>
             <li class="nav-item"> <a class="nav-link" href="{% url 'service:about_us' %}">About</a> </li>
             <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Pages </a>
                <ul class="dropdown-menu" >
                   <li>
                      <a href="#"> Agrovet</a>
                      <ul class="dropdown-menu" >
                         <li><a href="#">Products</a> </li>
                         <li><a href="#">Services</a> </li>
                         <li><a href="#">shops</a> </li>
                         <li><a href="#">locations</a> </li>
                      </ul>
                   </li>
                   <li>
                      <a href="#">Consultant</a>
                      <ul class="dropdown-menu" >
                         <li><a href="#">Services</a> </li>
                         <li><a href="#">Specialities</a> </li>
                         <li><a href="#">Finances</a> </li>
                      </ul>
                   </li>
                   <li>
                      <a href="team.html">Marketing</a>
                      <ul class="dropdown-menu" >
                         <li><a href="#">Sales</a> </li>
                         <li><a href="#">Products</a> </li>
                         <li><a href="#">Research</a> </li>
                      </ul>
                   </li>
                   <li>
                      <a href="#">Industry</a>
                      <ul class="dropdown-menu" >
                         <li><a href="#">Supplies</a> </li>
                         <li><a href="#">Tools</a> </li>
                         <li><a href="#">Equipment</a> </li>
                      </ul>
                   </li>
                   <li><a href="#">Gallery</a> </li>
                   <li><a href="#">Partners</a> </li>
                   <li><a href="{% url 'service:account' %}">My Account</a> </li>
                   <li><a href="#">Coming Soon</a> </li>
                </ul>
             </li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'service:contact' %}">Contact</a> </li>
          </ul>
          <ul class="topnav-right" style="display: inline">
             <li> <a class="mdonate" href="{% url 'service:account' %}"><span>Become a Partner</span></a> </li>
             <li> <a class="search-icon" href="#search"> <i class="fas fa-search"></i> </a> </li>
             <li class="login-reg"> <a href="{% url 'service:account' %}">Login</a> | <a href="{% url 'service:account' %}">Signup</a> </li>
          </ul>
        </div>
        </nav>
        </header>
        <div id="search">
        <button type="button" class="close">×</button>
        <form class="search-overlay-form">
        <input type="search" value="" placeholder="type keyword(s) here" />
        <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
        </form>
        </div>
        <!--Header End-->
   {% block body%}
   {% endblock %}
         <!--Footer Start-->
         <footer class="footer">
            <div class="footer-top wf100">
               <div class="container">
                  <div class="row">
                     <div class="col-lg-4 col-md-6 col-sm-6">
                        <!--Footer Widget Start-->
                        <div class="footer-widget">
                           <h4>About Turi Mei</h4>
                           <p> If anything’s hot in today’s economy, it’s saving money, including a broad range of green businesses helping people save energy, water, and other resources. Definitely, you can go with this business as it is a nothing but the future. </p>
                           <a href="#" class="lm">About us</a>
                        </div>
                        <!--Footer Widget End-->
                     </div>
                     <div class="col-lg-4 col-md-6 col-sm-6">
                        <!--Footer Widget Start-->
                        <div class="footer-widget">
                           <h4 class="pl-5">Our Promises</h4>
                           <ul class="quick-links ">
                              <li class="pl-5"><a href="#">Efficient Solutions</a></li>
                              <li class="pl-5"><a href="#">Financial Management</a></li>
                              <li class="pl-5"><a href="#">Farming Ideas</a></li>
                              <li class="pl-5"><a href="#">Cost Saving</a></li>
                           </ul>
                        </div>
                        <!--Footer Widget End-->
                     </div>
                     <div class="col-lg-4 col-md-6 col-sm-6 ">
                        <!--Footer Widget Start-->
                        <div class="footer-widget">
                           <h4>Our Vision and Mission</h4>
                            <p style="font-size: 14px">To connect everyday's farmers needs under one umbrella to efficiency, stability and economic prosperity of farmers.
                             We seek to empower farmers from all walks of life to achieve unrivalled success </p>

                        </div>
                        <!--Footer Widget End-->
                     </div>
                  </div>
               </div>
            </div>
            <div class="footer-copyr wf100">
               <div class="container">
                  <div class="row">
                     <div class="col-md-4 col-sm-4"> <img src="{% static 'images/my_images/logo3.png' %}" alt=""> </div>
                  </div>
               </div>
            </div>
         </footer>
         <!--Footer End-->
    </div>
      <!--   JS Files Start  -->
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'js/jquery-migrate-1.4.1.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
      <script src="{% static 'js/isotope.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>

   </body>
</html>